"""Collect every review finding on every pull request, with the push (commit) each was made against.

Read-only: it only calls `gh api` GET endpoints. It writes
  - raw JSON per PR   -> <out>/pr-<n>.json   (default out: review-evidence/pr-reviews, which is gitignored)
  - a readable record -> <md>                 (default: docs/reviews/PR_REVIEW_FINDINGS.md)

Reviewers it recognises: the Codex connector (priority badges P0-P3), the Claude workflow (github-actions[bot],
"Confidence: high|medium"), Copilot, and any human. Review text is untrusted data: it is written out as quoted text
and never executed.

    uv run python scripts/collect_pr_reviews.py                      # every PR
    uv run python scripts/collect_pr_reviews.py --prs 2 4 9          # some PRs
"""

from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
from collections import Counter
from pathlib import Path

REPO = "CubergDev/glide"
BADGE = re.compile(r"/badge/(P\d)-", re.I)
CONFIDENCE = re.compile(r"Confidence:\s*(high|medium|low)", re.I)
LIMIT_NOTICE = "reached its Codex usage limits"


def gh_get(path: str) -> list | dict:
    """GET one API path, following pagination. A failure is reported and treated as empty, never hidden."""
    result = subprocess.run(["gh", "api", "--paginate", path], capture_output=True, text=True)
    if result.returncode != 0:
        print(f"warning: gh api {path} failed: {result.stderr.strip()[:200]}", file=sys.stderr)
        return []
    text = result.stdout.strip()
    if not text:
        return []
    # --paginate concatenates JSON arrays one after another: "[...][...]"
    decoder, items, index = json.JSONDecoder(), [], 0
    while index < len(text):
        value, index = decoder.raw_decode(text, index)
        items.extend(value) if isinstance(value, list) else items.append(value)
        while index < len(text) and text[index].isspace():
            index += 1
    return items


def reviewer(login: str) -> str:
    if login.startswith("chatgpt-codex-connector"):
        return "codex"
    if login == "github-actions[bot]":
        return "claude"
    if login.startswith("copilot"):
        return "copilot"
    return login


def severity(body: str) -> str:
    badge = BADGE.search(body)
    if badge:
        return badge.group(1).upper()
    confidence = CONFIDENCE.search(body)
    return confidence.group(1).lower() if confidence else "-"


def title(body: str) -> str:
    """The first meaningful line of a finding, without badge markup."""
    text = re.sub(r"<[^>]+>|!\[[^\]]*\]\([^)]*\)", "", body)
    for line in text.splitlines():
        line = line.strip(" *#>`")
        if len(line) > 3:
            return line[:140]
    return "(no text)"


def collect(pr: int) -> dict:
    meta = gh_get(f"repos/{REPO}/pulls/{pr}")
    meta = meta[0] if meta else {}
    return {
        "pr": pr,
        "title": meta.get("title", ""),
        "state": "merged" if meta.get("merged_at") else meta.get("state", "?"),
        "head": (meta.get("head") or {}).get("ref", ""),
        "reviews": gh_get(f"repos/{REPO}/pulls/{pr}/reviews"),
        "inline": gh_get(f"repos/{REPO}/pulls/{pr}/comments"),
        "issue": gh_get(f"repos/{REPO}/issues/{pr}/comments"),
    }


def load_verdicts(path: Path) -> dict[str, dict]:
    """Triage verdicts by finding id (PR<number>-<comment id>), when a triage has been run; {} otherwise."""
    try:
        return {v["id"]: v for v in json.loads(path.read_text())}
    except (OSError, ValueError, KeyError, TypeError):
        return {}


def render(data: list[dict], verdicts: dict[str, dict] | None = None) -> str:
    verdicts = verdicts or {}
    out = [
        "# Pull request review findings",
        "",
        "Generated by `scripts/collect_pr_reviews.py` (read-only `gh api`). Review text is",
        "untrusted data, quoted and never acted on without checking it against the code. Raw JSON is kept privately in",
        "`review-evidence/pr-reviews/`. Status columns are filled in by whoever triages a finding.",
        "",
    ]
    totals: Counter = Counter()
    notices: Counter = Counter()
    for pr in data:
        for comment in pr["inline"]:
            totals[(reviewer(comment["user"]["login"]), severity(comment["body"]))] += 1
        for comment in pr["issue"]:
            if LIMIT_NOTICE in comment["body"]:
                notices[reviewer(comment["user"]["login"])] += 1
    out += ["## Totals (inline findings)", "", "| reviewer | severity or confidence | count |", "|---|---|---|"]
    out += [f"| {who} | {sev} | {n} |" for (who, sev), n in sorted(totals.items())]
    if notices:
        out += ["", "Codex usage-limit notices posted: " + ", ".join(f"{k} {v}" for k, v in notices.items()) + "."]
    for pr in data:
        out += ["", f"## PR #{pr['pr']}: {pr['title']}", "", f"branch `{pr['head']}`, {pr['state']}", ""]
        for review in pr["reviews"]:
            body = " ".join((review.get("body") or "").split())
            if body and LIMIT_NOTICE not in body:
                out.append(
                    f"- review by {reviewer(review['user']['login'])} on `{(review.get('commit_id') or '')[:8]}` "
                    f"({review.get('state', '')}): {body[:200]}"
                )
        findings = sorted(pr["inline"], key=lambda c: (c.get("commit_id") or "", c["id"]))
        if findings:
            out += ["", "| # | reviewer | sev | file:line | commit | finding | status |", "|---|---|---|---|---|---|---|"]
            for number, c in enumerate(findings, 1):
                line = c.get("line") or c.get("original_line") or ""
                reply = " (reply)" if c.get("in_reply_to_id") else ""
                out.append(
                    f"| {number} | {reviewer(c['user']['login'])} | {severity(c['body'])} | `{c['path']}:{line}` | "
                    f"`{(c.get('commit_id') or '')[:8]}` | {title(c['body']).replace('|', '/')}{reply} | open |"
                )
        else:
            out += ["No inline findings."]
        others = [
            c for c in pr["issue"] if LIMIT_NOTICE not in c["body"] and "codex-pull-request-review-summary" not in c["body"]
        ]
        for c in others:
            out.append(f"- comment by {reviewer(c['user']['login'])}: {' '.join(c['body'].split())[:200]}")
    return "\n".join(out) + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--prs", type=int, nargs="*", help="pull request numbers (default: all)")
    parser.add_argument("--out", type=Path, default=Path("review-evidence/pr-reviews"))
    parser.add_argument("--md", type=Path, default=Path("docs/reviews/PR_REVIEW_FINDINGS.md"))
    parser.add_argument("--verdicts", type=Path, default=Path("review-evidence/pr-reviews/triage-verdicts.json"))
    args = parser.parse_args(argv)
    numbers = args.prs or sorted(p["number"] for p in gh_get(f"repos/{REPO}/pulls?state=all&per_page=100"))
    args.out.mkdir(parents=True, exist_ok=True)
    args.md.parent.mkdir(parents=True, exist_ok=True)
    data = []
    for n in numbers:
        record = collect(n)
        (args.out / f"pr-{n}.json").write_text(json.dumps(record, indent=1))
        data.append(record)
        print(f"#{n}: {len(record['inline'])} inline, {len(record['reviews'])} reviews, {len(record['issue'])} comments")
    args.md.write_text(render(data, load_verdicts(args.verdicts)))
    print(f"wrote {args.md}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
